{{if ne .Values.branch.env "p0"}}
apiVersion: v1
kind: Secret
metadata:
  name: cx-conjur-b{{ .Values.branch.pvt}}
  namespace: {{ .Values.branch.osNameSpace}}
data:
  user-name: conjurUser
  api-key: conjurAPIKey
type: Opaque
{{- end -}}